on:
  push:
    path-ignore:
    - COPYING
    - COPYING.LESSER
    - .editorconfig
    - .gitignore
    - README.md

name: Continuous Integration

jobs:

  lint:
    name: Check linting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: elementary/actions/vala-lint@master

  run:
    name: Build, test and report coverage
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: dnf install -y vala libgee-devel meson glib2-devel gobject-introspection-devel
    - name: Build Vadi
      run: |
        meson build --prefix /usr
        ninja -C build
    - name: Test Vadi
      run: ninja -C build test
    - name: Report coverage
      run: |
        lcov -d build/lib -o lcov.info -c
        lcov -d build/lib -o lcov.info -r lcov.info "*/build/*"
        lcov -l lcov.info
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash) -f lcov.info
