on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/CI.yml
      - lib/**
      - tests/**
      - meson_options.txt
      - meson.build

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/CI.yml
      - lib/**
      - tests/**
      - meson_options.txt
      - meson.build

name: Continuous Integration

jobs:
  test:
    name: Test & report coverage
    runs-on: ubuntu-20.04
    container: fedora:34
    steps:
      - name: Install dependencies
        run: sudo dnf install -y vala libgee-devel glib2-devel gobject-introspection-devel meson lcov git libasan

      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Build Vadi
        run: |
          meson build --prefix /usr -Db_coverage=true -Db_sanitize=address -Dtests=true
          ninja -C build

      - name: Test Vadi
        run: ninja -C build test

      - name: Report coverage
        run: |
          lcov -d build/lib -o lcov.info -c
          lcov -d build/lib -o lcov.info -r lcov.info "*/build/*"
          lcov -l lcov.info

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
