on:
  push:
    path-ignore:
    - COPYING
    - COPYING.LESSER
    - .editorconfig
    - .gitignore
    - README.md
name: Continuous Integration
jobs:
  lint:
    name: Check linting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: elementary/actions/vala-lint@master
  build:
    name: Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Install dependencies
      run: |
        dnf install -y vala libgee-devel meson glib2-devel gobject-introspection-devel
    - name: Build Vadi
      run: |
        meson build --prefix /usr
        ninja -C build
    - name: Upload Vadi build files
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
  test:
    name: Test
    runs-on: ubuntu-latest
    container: fedora:latest
    needs: build
    steps:
    - uses: actions/download-artifacts@v2
    - name: Install dependencies
      run: dnf install -y meson libgee glib2
    - name: Ensure execution permissions on tests
      run: chmod -v +x build/tests/test-*
    - name: Test Vadi
      run: meson test -C build --no-rebuild --print-errorlogs
